version: '3'
# create a permanent network first
# > docker network create docker-network --subnet 172.24.24.0/24
networks:
  front:
    external:
      name: docker-network
  back:
    external:
      name: docker-network
