version: '3'
services:
  postgres:
    build: './docker/postgres'
    ports:
      - 5432:5432
    networks:
      - back
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'pdc-local'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ./db/postgres:/var/lib/postgresql/data/pgdata
  mongo:
    image: 'mongo:4.0'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'mongo'
      MONGO_INITDB_ROOT_PASSWORD: 'mongo'
      MONGO_INITDB_DATABASE: 'pdc-local'
    volumes:
      - ./db/mongo:/data/db
    networks:
      - front
      - back

  redis:
    image: 'redis:4'
    ports:
      - 6379:6379
    networks:
      - front
      - back

  api:
    build: './docker/api'
    volumes:
      - ./api:/code
    working_dir: '/code'
    command: 'yarn start:http:dev'
    ports:
      - 8080:8080
      - 9229:9229
    environment:
      NODE_ENV: local
      PORT: 8080
      # APP_API_URL: 'http://localhost:8080'
      # APP_APP_URL: 'http://localhost:4200'
      APP_SUPERUSER_EMAIL: admin@example.com
      APP_SUPERUSER_PASSWORD: admin1234
      APP_MONGO_URL: mongodb://mongo:mongo@mongo:27017
      APP_MONGO_DB: pdc-local
      APP_REDIS_URL: redis://redis:6379
    networks:
      - front
      - api
      - back
    depends_on:
      - mongo
      - redis

  worker:
    build: './docker/api'
    volumes:
      - ./api:/code
    working_dir: '/code'
    command: 'yarn start:queue'
    ports:
      - 9230:9230
    environment:
      APP_WORKER: 'true'
      APP_MONGO_URL: mongodb://mongo:mongo@mongo:27017
      APP_MONGO_DB: pdc-local
      APP_REDIS_URL: redis://redis:6379
    networks:
      - front
      - api
      - back
    depends_on:
      - mongo
      - redis

  dashboard:
    build: './docker/dashboard'
    tty: true
    volumes:
      - ./dashboard:/code
    working_dir: '/code'
    command: 'ng serve --host 0.0.0.0'
    ports:
      - 4200:4200
    networks:
      - front
      - api
    depends_on:
      - api

  editor:
    image: 'swaggerapi/swagger-editor'
    ports:
      - 8081:8080

networks:
  front:
  api:
  back:
