version: '3.5'
services:
  postgres:
    build:
      context: ./docker/postgres
      shm_size: 4gb
    shm_size: 4gb
    ports:
      - 5432:5432
    networks:
      - front
      - back
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'pdc-local'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ./db/postgres:/var/lib/postgresql/data/pgdata

  pgadmin:
    build: ./docker/pgadmin
    networks:
      - front
      - back
    ports:
      - 5050:80
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    volumes:
      - ./db/pgadmin:/pgadmin4/volume

  redis:
    build: './docker/redis'
    ports:
      - 6379:6379
    networks:
      - front
      - back

  api:
    build: './docker/api'
    volumes:
      - .:/code
    working_dir: '/code/api'
    command: 'yarn start:http'
    ports:
      - 8080:8080
    env_file: ./api/.env
    environment:
      NODE_ENV: local
      PORT: 8080
    networks:
      - front
      - back
    depends_on:
      - redis
      - postgres

  worker:
    build: './docker/api'
    volumes:
      - ./api:/code
    working_dir: '/code'
    command: 'yarn start:queue'
    env_file: ./api/.env
    environment:
      APP_WORKER: 'true'
    networks:
      - front
      - back
    depends_on:
      - redis
      - postgres

  printer:
    build: './docker/printer'
    volumes:
      - .:/code
    working_dir: '/code/printer'
    command: 'yarn start'
    ports:
      - 3000:3000
    env_file: ./printer/.env
    environment:
      NODE_ENV: production
      PORT: 3000
    networks:
      - front
      - back

  arena:
    build: ./docker/arena
    environment:
      APP_REDIS_URL: redis://redis:6379
    ports:
      - 4567:4567
    networks:
      - front
      - back
    depends_on:
      - redis
networks:
  front:
  back:
