version: '3'
services:
  mongo:
    image: "mongo:3.6"
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo"
      MONGO_INITDB_ROOT_PASSWORD: "mongo"
      MONGO_INITDB_DATABASE: "pdc-collector"
    volumes:
    - ./db/mongo:/data/db
    networks:
    - front
    - back

  api:
    build: "./docker/api"
    volumes:
    - ./api:/code
    working_dir: "/code"
    command: "nodemon --inspect=0.0.0.0:9229"
    ports:
    - 8080:8080
    - 9229:9229
    env_file: .env
    environment:
      CONFIG_DIR: '/code/config'
    networks:
    - front
    - api
    - back
    depends_on:
    - mongo

  aom:
    build: "./docker/aom"
    tty: true
    volumes:
    - ./dashboard-aom:/code
#      - ./common:/common <-- PLUS TARD
    working_dir: "/code"
    command: "yarn"
    ports:
    - 4200:4200
    networks:
    - front
    - api
    depends_on:
    - api

  operator:
    build: "./docker/operator"
    tty: true
    volumes:
      - ./dashboard-operator:/code
#      - ./common:/common <-- PLUS TARD
    working_dir: "/code"
    command: "yarn"
    ports:
      - 4400:4400
    networks:
      - front
      - api
    depends_on:
      - api

  registry:
    build: "./docker/registry"
    tty: true
    volumes:
      - ./dashboard-registry:/code
    #      - ./common:/common <-- PLUS TARD
    working_dir: "/code"
    command: "yarn"
    ports:
      - 4600:4600
    networks:
      - front
      - api
    depends_on:
      - api



networks:
  front:
  api:
  back:
