version: '3.5'
services:
  postgres:
    build:
      context: ./docker/postgres
      shm_size: 4gb
    shm_size: 4gb
    ports:
      - 5432:5432
    networks:
      - front
      - back
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'local'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ./db/postgres:/var/lib/postgresql/data/pgdata

  redis:
    build: './docker/redis'
    ports:
      - 6379:6379
    networks:
      - front
      - back

  mailhog:
    image: mailhog/mailhog:v1.0.1
    # enable the chaos monkey (Jim) with a very low bandwidth
    # https://github.com/mailhog/MailHog/blob/master/docs/JIM.md
    # command: -invite-jim -jim-linkspeed-affect=1 -jim-linkspeed-min=10
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MH_CORS_ORIGIN: '*'
    networks:
      - front
      - back

  migrator:
    build:
      dockerfile: ../../docker/migrator/Dockerfile
      context: ./api/db
    volumes:
      - ./api/db:/data
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@postgres:5432/local'
    networks:
      - back
    depends_on:
      - postgres

  api:
    build: './docker/api'
    volumes:
      - .:/code
    working_dir: '/code/api'
    command: 'bash -c "yarn start:http | pino-pretty"'
    tty: true
    ports:
      - 8080:8080
    env_file: ./api/.env
    environment:
      PORT: 8080
    networks:
      - front
      - back
    depends_on:
      - redis
      - postgres
      - mailhog

  worker:
    build: './docker/api'
    volumes:
      - ./api:/code
    working_dir: '/code'
    command: 'bash -c "yarn start:queue | pino-pretty"'
    tty: true
    env_file: ./api/.env
    environment:
      APP_WORKER: 'true'
    networks:
      - front
      - back
    depends_on:
      - redis
      - postgres
      - mailhog

  lint:
    build: './docker/lint'
    tty: true
    volumes:
      - ./api:/code/api:ro
      - ./dashboard:/code/dashboard:ro

networks:
  front:
  back:
