headers:
  - name: Nom de l'opérateur
    path: operator.name
    type: ascii
  - name: id du passager ou conducteur
    path: traveler_hash
    type: int
  - name: latitude au départ
    path: start.lat
    type: int
  - name: longitude au départ
    path: start.lng
    type: int
  - name: date depart
    path: start.date
    type: int
  - name: insee départ
    path: start.insee
    type: int
  - name: lat arrivée
    path: end.lat
    type: int
  - name: lon arrivée
    path: end.lng
    type: int
  - name: date arrivée
    path: end.date
    type: int
  - name: insee arrivée
    path: end.insee
    type: int
