headers:
  - name: Nom de l'opérateur
    path: operator.nom_commercial
    type: ascii
  - name: ID trajet
    path: journey_id
    type: ascii
  - name: Classe
    path: validation.rank
    type: ascii
  - name: Occupant du véhicule
    path: is_driver
    type: ascii
    transform: driverToName
  - name: Age
    path: over_18
    type: ascii
    transform: isAdulte
  - name: Id du passager ou conducteur
    path: traveler_hash
    type: int
  - name: Latitude au départ
    path: start.lat
    type: int
  - name: Longitude au départ
    path: start.lng
    type: int
  - name: Date départ
    path: start.date
    type: int
    transform: date
  - name: Insee départ
    path: start.insee
    type: int
  - name: Latitude à arrivée
    path: end.lat
    type: int
  - name: Longitude à arrivée
    path: end.lng
    type: int
  - name: Date arrivée
    path: end.date
    type: int
    transform: date
  - name: Insee arrivée
    path: end.insee
    type: int
