roles:
  - slug: admin
    name: Admin
    permissions:
      - proof_create
      - proof_read
      - proof_edit
      - proof_delete
      - user_list
      - user_invite
      - user_create
      - user_read
      - user_edit
      - user_delete
  - slug: user
    name: User
    permissions:
      - proof_read
      - user_list
