name: 'Analysis - Unit test'

on: pull_request

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: sh rebuild.sh
        working-directory: api
      - name: Run Unit test
        run: yarn test:unit
        working-directory: api
