name: 'Analysis - Audit dependencies'

on: pull_request

defaults:
  run:
    shell: bash

jobs:
  code-audit:
    name: Code audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: 'Audit API dependencies'
        run: yarn audit --level moderate --groups dependencies || [[ $? -ge 8 ]] && exit 1 || exit 0
        working-directory: api
      - name: 'Audit dashboard dependencies'
        run: yarn audit --level moderate --groups dependencies || [[ $? -ge 8 ]] && exit 1 || exit 0
        working-directory: dashboard
