name: 'Analysis - Audit dependencies'

on: pull_request

defaults:
  run:
    shell: bash

jobs:
  code-audit:
    name: Code audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 'Audit API dependencies'
        run: npm audit --audit-level moderate --workspaces --include-workspace-root && exit 0 || $([[ $? -ge 8 ]] && exit 1 || exit 0)
        working-directory: api
      
      - name: 'Audit dashboard dependencies'
        run: npm audit --audit-level moderate --workspaces --include-workspace-root && exit 0 || $([[ $? -ge 8 ]] && exit 1 || exit 0)
        working-directory: dashboard
