name: 'Analysis - E2E test'

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  e2e:
    name: Test e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Start
        run: ./tool.sh e2e
      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: videos
          path: /tmp/cypress/videos/
          retention-days: 3
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: /tmp/cypress/screenshots/
          retention-days: 3
