name: Deploy documentation - production
on:
  push:
    branches: [dev]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: doc/package-lock.json

      - name: Install and Build 🔧
        run: |
          cd doc
          npm ci
          npm run gen
          NODE_OPTIONS=--openssl-legacy-provider npm run build

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.FRONT_DEPLOY_KEY }}

      - name: Deploy 🚀
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.FRONT_HOST }}
          username: ${{ secrets.FRONT_USERNAME }}
          key: ${{ secrets.FRONT_DEPLOY_KEY }}
          source: doc/dist
          target: www/doc
          rm: true
